version: "3.1"

services:
    go-hex:
        image: docker.pkg.github.com/capioteknologi/go-hex/development:latest
        container_name: go-hex
        env_file:
            - .env
        ports:
        - 3000:3000
        volumes:
          - ./google-credentials.json:/app/google-credentials.json
        restart: always
        entrypoint: bash -c "./application migrate up && ./application api"

    go-hex-cron-cleanup:
        image: docker.pkg.github.com/capioteknologi/go-hex/development:latest
        container_name: go-hex-cron-cleanup
        env_file:
            - .env
        volumes:
          - ./google-credentials.json:/app/google-credentials.json
        restart: always
        depends_on:
            - go-hex
        command: ["cron", "cleanup"]
          